---
os: osx
osx_image: xcode10
language: swift
podfile: Podfile
script: xcodebuild clean build -workspace Test2.xcworkspace -scheme "Test2" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.0,name=iPhone XR" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO